### ISSUE TITLE
Use Chart Widget in WinForms not working anymore (using WebBrowse built in)

### ISSUE THREAD

**Issue by o-sense** [tradingview/awesome-tradingview#5]
Hi,
We used to show your chart widget within WinForms app normally, suddenly last month it stopped from working and keep showing the loading rotator. Have you stopped supporting that for old browser? because using my chrome it opens normally, but in the WinForms that has the built-in Web Browse control it is not.
Is there anything we can do? I don't want to use CEFSharp or any outside controls since they require higher framework version.
Thanks.

**Comment by timocov** [comment]
How it's related to this repo?

**Comment by o-sense** [comment]
It's the only repo I found the word (widget) on it. Am not talking about your library itself that we can customize and add our own candles. I want the public widget to put it in winforms app with old web browse from Microsoft

**Comment by timocov** [comment]
Please contact tradingview's support via website please.
